name: Build Check - All LTS Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build-check:
    strategy:
      fail-fast: false
      matrix:
        kernel_config:
          # Android 12 - Kernel 5.10 LTS
          #- android_version: "android12"
          #  kernel_version: "5.10"
          #  sub_level: "X"
          #  os_patch_level: "lts"
          #
          ## Android 13 - Kernel 5.10 LTS
          #- android_version: "android13"
          #  kernel_version: "5.10"
          #  sub_level: "X"
          #  os_patch_level: "lts"
          #
          ## Android 13 - Kernel 5.15 LTS
          #- android_version: "android13"
          #  kernel_version: "5.15"
          #  sub_level: "X"
          #  os_patch_level: "lts"
          #
          ## Android 14 - Kernel 5.15 LTS
          #- android_version: "android14"
          #  kernel_version: "5.15"
          #  sub_level: "X"
          #  os_patch_level: "lts"
          
          # Android 14 - Kernel 6.1 LTS
          - android_version: "android14"
            kernel_version: "6.1"
            sub_level: "X"
            os_patch_level: "lts"
          
          # Android 14 - Kernel 6.1.134 Testing
          - android_version: "android14"
            kernel_version: "6.1"
            sub_level: "134"
            os_patch_level: "2025-05"
          
          # Android 15 - Kernel 6.6 LTS
          #- android_version: "android15"
          #  kernel_version: "6.6"
          #  sub_level: "X"
          #  os_patch_level: "lts"

    name: Build Check
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.kernel_config.android_version }}
      kernel_version: ${{ matrix.kernel_config.kernel_version }}
      sub_level: ${{ matrix.kernel_config.sub_level }}
      os_patch_level: ${{ matrix.kernel_config.os_patch_level }}