name: Kernel Config - A14 6.1

permissions:
    contents: write # Allow writing to repository contents
    actions: write # Allows triggering actions

on:
    workflow_call:
        inputs:
            use_make:
                required: true
                type: boolean

jobs:
    build-kernels-a14-6-1:
        strategy:
            fail-fast: true
            matrix:
                include:
                    - sub_level: "124"
                      os_patch_level: "2025-02"
                    #- sub_level: "X"
                    #  os_patch_level: "lts"
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            android_version: "android14"
            kernel_version: "6.1"
            sub_level: ${{ matrix.sub_level }}
            os_patch_level: ${{ matrix.os_patch_level }}

            use_make: ${{ inputs.use_make }}
