name: Build Kernels

permissions:
    contents: write
    actions: write

on:
    workflow_dispatch:
        inputs:
            use_make:
                description: "Build with MAKE?"
                required: true
                type: boolean
                default: true

jobs:
    build-a14-6-1:
        uses: ./.github/workflows/kernel-a14-6-1.yml
        secrets: inherit
        with:
            use_make: ${{ inputs.use_make }}
